version: "2"
services:
  orthanc-pacs:
    build: orthanc-pacs
    restart: unless-stopped
    ports: ["8042:8042"]
    volumes: ["orthanc-storage-pacs:/var/lib/orthanc/db:Z"]
  orthanc-middleman:
    build: orthanc-middleman
    restart: unless-stopped
    ports: ["8043:8042"]
    environment:
      ORTHANC__NAME: "orthanc-python"

      VERBOSE_ENABLED: "false"
      VERBOSE_STARTUP: "false"
      ORTHANC__PYTHON_SCRIPT: "/python/test.py"
      ORTHANC__PYTHON_VERBOSE: "false"
    volumes: ["orthanc-storage-middleman:/var/lib/orthanc/db:Z"]
  orthanc-modality:
    build: orthanc-modality
    restart: unless-stopped
    ports: ["8044:8042"]
    volumes: ["orthanc-storage-modality:/var/lib/orthanc/db:Z"]
volumes:
  orthanc-storage-pacs:
  orthanc-storage-middleman:
  orthanc-storage-modality:
